"""Add condition reports payments and audit log

Revision ID: fde374b1e7a8
Revises: c119fa251c95
Create Date: 2026-05-17 21:06:48.653321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fde374b1e7a8'
down_revision: Union[str, Sequence[str], None] = 'c119fa251c95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condition_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenancy_id', sa.UUID(), nullable=True),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('signed_by_operator', sa.Boolean(), nullable=True),
    sa.Column('signed_by_tenant', sa.Boolean(), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenancy_id'], ['tenancies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenancy_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('method', sa.Enum('upi', 'cash', 'bank_transfer', 'other', name='paymentmethod'), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenancy_id'], ['tenancies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # The tenancystatus enum already exists from the initial migration, so reference it via postgresql.ENUM
    from sqlalchemy.dialects import postgresql
    tenancystatus_enum = postgresql.ENUM('inquiry', 'confirmed', 'active', 'notice_period', 'vacated', 'cancelled', name='tenancystatus', create_type=False)
    op.create_table('tenancy_status_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenancy_id', sa.UUID(), nullable=True),
    sa.Column('from_status', tenancystatus_enum, nullable=True),
    sa.Column('to_status', tenancystatus_enum, nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenancy_id'], ['tenancies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('condition_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=True),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('condition', sa.Enum('good', 'fair', 'damaged', 'missing', name='conditionrating'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('deduction_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('disputed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['condition_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('operators', sa.Column('password_hash', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('password_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'password_hash')
    op.drop_column('operators', 'password_hash')
    op.drop_table('condition_items')
    op.drop_table('tenancy_status_log')
    op.drop_table('payments')
    op.drop_table('condition_reports')
    # ### end Alembic commands ###
